name: "Devspace Pull-Request automation"
run-name: "devspace Pull-Request automation - ${{ github.event.client_payload.uuid }}"

on:
  repository_dispatch:
    types: [devspace_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: wait for build
        run: sleep 300
