name: "Devspace Pull-Request automation"
run-name: "devspace Pull-Request automation - ${{ github.event.client_payload.uuid }}"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [devspace_build]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$GITHUB_CONTEXT"
      - name: set-version
        run: |
           echo '### Hello world!' >> $GITHUB_STEP_SUMMARY
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
    
  deploy:
    runs-on: ubuntu-latest
    environment: qa
    needs: ["build"]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$GITHUB_CONTEXT"
      - name: set-version
        run: |
           echo '### Hello world!' >> $GITHUB_STEP_SUMMARY
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: wait for build
        run: sleep 180
