# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Analyze

on:
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: sleep 30

    - name: Test
      run: sleep 30
